# Generated by Django 5.1.3 on 2025-04-20 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('bucket', models.CharField(max_length=100)),
                ('city_name', models.CharField(max_length=100)),
                ('aqi', models.FloatField()),
                ('theme', models.CharField(max_length=50)),
                ('presigned_url', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GSODStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_id', models.CharField(max_length=10, unique=True)),
                ('usaf', models.CharField(max_length=6)),
                ('wban', models.CharField(max_length=5)),
                ('name', models.CharField(max_length=100)),
                ('country', models.CharField(blank=True, max_length=2)),
                ('state', models.CharField(blank=True, max_length=2)),
                ('icao', models.CharField(blank=True, max_length=4)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('elevation_m', models.FloatField()),
                ('begin_date', models.CharField(max_length=8)),
                ('end_date', models.CharField(blank=True, max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='OpenAQData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('bucket', models.CharField(max_length=100)),
                ('city_name', models.CharField(max_length=100)),
                ('parameter', models.CharField(max_length=10)),
                ('year_start', models.IntegerField()),
                ('year_end', models.IntegerField()),
                ('record_count', models.IntegerField()),
                ('location_ids', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='NOAAData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('bucket', models.CharField(max_length=100)),
                ('city_name', models.CharField(max_length=100)),
                ('year_start', models.IntegerField()),
                ('year_end', models.IntegerField()),
                ('record_count', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airquality_data.gsodstation')),
            ],
        ),
        migrations.CreateModel(
            name='MergedData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('train_filename', models.CharField(max_length=255)),
                ('test_filename', models.CharField(max_length=255)),
                ('bucket', models.CharField(max_length=100)),
                ('unhealthy_threshold', models.FloatField()),
                ('train_record_count', models.IntegerField()),
                ('test_record_count', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('noaa_dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airquality_data.noaadata')),
                ('openaq_dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airquality_data.openaqdata')),
            ],
        ),
        migrations.CreateModel(
            name='TrainedModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100)),
                ('model_path', models.CharField(max_length=255)),
                ('bucket', models.CharField(max_length=100)),
                ('leaderboard', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('merged_dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airquality_data.mergeddata')),
            ],
        ),
    ]
