# Generated by Django 5.1.3 on 2025-04-21 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airquality_data', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gsodstation',
            old_name='name',
            new_name='station_name',
        ),
    ]
