# Generated by Django 5.1.3 on 2025-04-21 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airquality_data', '0002_rename_name_gsodstation_station_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gsodstation',
            name='country',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='gsodstation',
            name='icao',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='gsodstation',
            name='state',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='gsodstation',
            name='station_name',
            field=models.CharField(max_length=128),
        ),
    ]
