# Generated by Django 5.1.3 on 2025-04-21 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airquality_data', '0003_alter_gsodstation_country_alter_gsodstation_icao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gsodstation',
            name='station_id',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
