# Generated by Django 5.1.3 on 2025-04-22 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("airquality_data", "0004_alter_gsodstation_station_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mergeddata",
            name="bucket",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="mergeddata",
            name="noaa_dataset",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="airquality_data.noaadata",
            ),
        ),
        migrations.AlterField(
            model_name="mergeddata",
            name="openaq_dataset",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="airquality_data.openaqdata",
            ),
        ),
        migrations.AlterField(
            model_name="mergeddata",
            name="test_filename",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="mergeddata",
            name="test_record_count",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="mergeddata",
            name="train_filename",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="mergeddata",
            name="train_record_count",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="mergeddata",
            name="unhealthy_threshold",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
